# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Manage a collaborator
on:
  workflow_dispatch:
    inputs:
      email:
        description: "The collaborator's email address"
        required: true
        type: string
      add:
        description: "Checked to add, unchecked to remove"
        required: false
        default: true
        type: boolean
jobs:
  collaborator:
    name: Add or remove a collaborator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Look up the Slack user by email
        id: email
        uses: slackapi/slack-github-action@v2
        with:
          method: users.lookupByEmail # https://docs.slack.dev/reference/methods/users.lookupByEmail/
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            email: ${{ inputs.email }}

      - name: Gather the display name
        if: ${{ steps.email.outputs.ok }}
        run: |
          SLACK_USER_ID=$(echo '${{ steps.email.outputs.response }}' | jq -r '.user.id')
          SLACK_DISPLAY_NAME=$(echo '${{ steps.email.outputs.response }}' | jq -r '.user.profile.display_name // .user.real_name')
          echo "SLACK_USER_ID=$SLACK_USER_ID" >> "$GITHUB_ENV"
          echo "SLACK_DISPLAY_NAME=$SLACK_DISPLAY_NAME" >> "$GITHUB_ENV"

      - name: Add or remove the collaborator
        if: ${{ steps.email.outputs.ok }}
        uses: slackapi/slack-github-action/cli@v2
        with:
          command: "collaborators ${{ inputs.add && 'add' || 'remove' }} ${{ inputs.email }}"
          token: ${{ secrets.SLACK_SERVICE_TOKEN }}

      - name: Post a confirmation message
        if: ${{ steps.email.outputs.ok }}
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage # https://docs.slack.dev/reference/methods/chat.postMessage/
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "<@${{ env.SLACK_USER_ID }}> (${{ env.SLACK_DISPLAY_NAME }}) was ${{ inputs.add && 'added to' || 'removed from' }} the app collaborators."
