# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Validate the app manifest
on:
  pull_request:
jobs:
  validate:
    name: Check the app manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Validate the manifest
        uses: slackapi/slack-github-action/cli@v2
        with:
          command: "manifest validate --app ${{ vars.SLACK_APP_ID }}"
          token: ${{ secrets.SLACK_SERVICE_TOKEN }}
