name: "Slack: Send to Slack"
author: "slackapi"
description: "Send data to Slack to start a Slack workflow in Workflow Builder, call a Slack API method, post a message into a channel, or run a Slack CLI command"
inputs:
  api:
    description: "A custom API URL to send Slack API method requests to."
    required: false
  command:
    description: "A Slack CLI command to run without the 'slack' prefix."
    required: false
  errors:
    default: "false"
    description: "If the step exits with an error on errors or continues."
    required: false
  method:
    description: "The Slack API method to call."
    required: false
  payload:
    description: "Attributes that create the content of the request using JSON or YAML."
    required: false
  payload-delimiter:
    description: "Field separator for nested attributes in the input payload."
    required: false
  payload-file-path:
    description: "Path to a file containing a valid input payload made of JSON or YAML."
    required: false
  payload-templated:
    default: "false"
    description: "If templated variables in input payloads should be replaced."
    required: false
  proxy:
    description: "An optional proxied route for HTTPS connections."
    required: false
  retries:
    default: "5"
    description: "The strategy to use when performing retried requests."
  token:
    description: "The authentication value used with the Slack API."
    required: false
  version:
    description: "The version of the Slack CLI to install."
    required: false
  webhook:
    description: "A location for posting request payloads."
    required: false
  webhook-type:
    description: "Option to use either an incoming webhook or webhook trigger."
    required: false
outputs:
  ok:
    description: "If the request completed without returning errors."
    value: ${{ steps.slack-send.outputs.ok || steps.slack-cli.outputs.ok }}
  response:
    description: "A JSON stringified version of the Slack API response."
    value: ${{ steps.slack-send.outputs.response || steps.slack-cli.outputs.response }}
  time:
    description: "The Unix epoch time that the step completed."
    value: ${{ steps.slack-send.outputs.time || steps.slack-cli.outputs.time }}
  channel_id:
    description: "The channel ID returned with some of the Slack API methods."
    value: ${{ steps.slack-send.outputs.channel_id }}
  thread_ts:
    description: "The timestamp of a parent Slack message with threaded replies."
    value: ${{ steps.slack-send.outputs.thread_ts }}
  ts:
    description: "The timestamp of a Slack message or event in the response."
    value: ${{ steps.slack-send.outputs.ts }}
runs:
  using: composite
  steps:
    - name: Validate inputs
      if: inputs.command != '' && (inputs.method != '' || inputs.webhook != '')
      shell: bash
      run: |
        echo "::error::The 'command' input cannot be combined with 'method' or 'webhook' inputs."
        exit 1

    - name: Send data to Slack
      id: slack-send
      if: inputs.command == ''
      shell: bash
      run: node "${{ github.action_path }}/dist/index.js"
      env:
        INPUT_API: ${{ inputs.api }}
        INPUT_ERRORS: ${{ inputs.errors }}
        INPUT_METHOD: ${{ inputs.method }}
        INPUT_PAYLOAD: ${{ inputs.payload }}
        INPUT_PAYLOAD-DELIMITER: ${{ inputs.payload-delimiter }}
        INPUT_PAYLOAD-FILE-PATH: ${{ inputs.payload-file-path }}
        INPUT_PAYLOAD-TEMPLATED: ${{ inputs.payload-templated }}
        INPUT_PROXY: ${{ inputs.proxy }}
        INPUT_RETRIES: ${{ inputs.retries }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_WEBHOOK: ${{ inputs.webhook }}
        INPUT_WEBHOOK-TYPE: ${{ inputs.webhook-type }}

    - name: Check if Slack CLI already exists
      id: slack-cli-check
      if: inputs.command != ''
      shell: bash
      run: |
        if command -v slack &> /dev/null; then
          echo "cli-exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "cli-exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Cache Slack CLI
      if: inputs.command != '' && steps.slack-cli-check.outputs.cli-exists != 'true'
      id: cache-cli
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ${{ runner.os == 'Windows' && format('{0}\AppData\Local\slack-cli', env.USERPROFILE) || format('{0}/.slack/bin', env.HOME) }}
        key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Add Slack CLI to PATH (Linux/macOS)
      if: inputs.command != '' && steps.slack-cli-check.outputs.cli-exists != 'true' && runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.slack/bin" >> "$GITHUB_PATH"

    - name: Add Slack CLI to PATH (Windows)
      if: inputs.command != '' && steps.slack-cli-check.outputs.cli-exists != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.slack\bin"

    - name: Install Slack CLI (Linux/macOS)
      if: >-
        inputs.command != '' &&
        steps.slack-cli-check.outputs.cli-exists != 'true' &&
        steps.cache-cli.outputs.cache-hit != 'true' &&
        runner.os != 'Windows'
      shell: bash
      run: |
        if [ -n "$SLACK_CLI_VERSION" ]; then
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- -v "$SLACK_CLI_VERSION"
        else
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s
        fi
      env:
        SLACK_CLI_VERSION: ${{ inputs.version }}

    - name: Install Slack CLI (Windows)
      if: >-
        inputs.command != '' &&
        steps.slack-cli-check.outputs.cli-exists != 'true' &&
        steps.cache-cli.outputs.cache-hit != 'true' &&
        runner.os == 'Windows'
      shell: pwsh
      run: |
        if ($env:SLACK_CLI_VERSION) {
          $installer = Join-Path $env:TEMP "install-slack-cli.ps1"
          Invoke-WebRequest -Uri "https://downloads.slack-edge.com/slack-cli/install-windows-dev.ps1" -OutFile $installer
          & $installer -v $env:SLACK_CLI_VERSION
        } else {
          irm https://downloads.slack-edge.com/slack-cli/install-windows-dev.ps1 | iex
        }
      env:
        SLACK_CLI_VERSION: ${{ inputs.version }}

    - name: Run Slack CLI command
      id: slack-cli
      if: inputs.command != ''
      shell: bash
      env:
        SLACK_COMMAND: ${{ inputs.command }}
        SLACK_TOKEN: ${{ inputs.token }}
      run: |
        args="$SLACK_COMMAND --skip-update"
        if [ -n "$SLACK_TOKEN" ]; then
          args="$args --token $SLACK_TOKEN"
        fi

        set +e
        output=$(slack $args 2>&1)
        exit_code=$?
        set -e

        echo "ok=$([ $exit_code -eq 0 ] && echo 'true' || echo 'false')" >> "$GITHUB_OUTPUT"
        echo "time=$(date +%s)" >> "$GITHUB_OUTPUT"

        echo "response<<SLACKCLIEOF" >> "$GITHUB_OUTPUT"
        echo "$output" >> "$GITHUB_OUTPUT"
        echo "SLACKCLIEOF" >> "$GITHUB_OUTPUT"

        if [ $exit_code -ne 0 ]; then
          echo "::error::Slack CLI command failed with exit code $exit_code"
          exit $exit_code
        fi
