name: "Slack: Run CLI Command"
author: "slackapi"
description: "Install the Slack CLI and run a command in a GitHub Actions workflow"
inputs:
  command:
    description: "A Slack CLI command to run without the 'slack' prefix."
    required: true
  token:
    description: "A service token passed as the '--token' flag to the CLI command."
    required: false
  version:
    description: "The version of the Slack CLI to install. Defaults to the latest."
    required: false
outputs:
  ok:
    description: "If the command completed with a '0' exit code."
    value: ${{ steps.slack-cli.outputs.ok }}
  response:
    description: "The standard output from the CLI command."
    value: ${{ steps.slack-cli.outputs.response }}
  time:
    description: "The Unix epoch time that the step completed."
    value: ${{ steps.slack-cli.outputs.time }}
runs:
  using: composite
  steps:
    - name: Check if Slack CLI already exists
      id: slack-cli-check
      shell: bash
      run: |
        if command -v slack &> /dev/null; then
          echo "cli-exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "cli-exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Cache Slack CLI
      if: steps.slack-cli-check.outputs.cli-exists != 'true'
      id: cache-cli
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ${{ runner.os == 'Windows' && format('{0}\AppData\Local\slack-cli', env.USERPROFILE) || format('{0}/.slack/bin', env.HOME) }}
        key: slack-cli-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Add Slack CLI to PATH (Linux/macOS)
      if: steps.slack-cli-check.outputs.cli-exists != 'true' && runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.slack/bin" >> "$GITHUB_PATH" # zizmor: ignore[github-env]

    - name: Add Slack CLI to PATH (Windows)
      if: steps.slack-cli-check.outputs.cli-exists != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.slack\bin" # zizmor: ignore[github-env]

    - name: Install Slack CLI (Linux/macOS)
      if: >-
        steps.slack-cli-check.outputs.cli-exists != 'true' &&
        steps.cache-cli.outputs.cache-hit != 'true' &&
        runner.os != 'Windows'
      shell: bash
      run: |
        if [ -n "$SLACK_CLI_VERSION" ]; then
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s -- -v "$SLACK_CLI_VERSION"
        else
          curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s
        fi
      env:
        SLACK_CLI_VERSION: ${{ inputs.version }}

    - name: Install Slack CLI (Windows)
      if: >-
        steps.slack-cli-check.outputs.cli-exists != 'true' &&
        steps.cache-cli.outputs.cache-hit != 'true' &&
        runner.os == 'Windows'
      shell: pwsh
      run: |
        if ($env:SLACK_CLI_VERSION) {
          $installer = Join-Path $env:TEMP "install-slack-cli.ps1"
          Invoke-WebRequest -Uri "https://downloads.slack-edge.com/slack-cli/install-windows-dev.ps1" -OutFile $installer
          & $installer -v $env:SLACK_CLI_VERSION
        } else {
          irm https://downloads.slack-edge.com/slack-cli/install-windows-dev.ps1 | iex
        }
      env:
        SLACK_CLI_VERSION: ${{ inputs.version }}

    - name: Run Slack CLI command
      id: slack-cli
      shell: bash
      env:
        SLACK_COMMAND: ${{ inputs.command }}
        SLACK_TOKEN: ${{ inputs.token }}
      run: |
        args="$SLACK_COMMAND --skip-update"
        if [ -n "$SLACK_TOKEN" ]; then
          args="$args --token $SLACK_TOKEN"
        fi

        set +e
        output=$(slack $args 2>&1)
        exit_code=$?
        set -e

        echo "ok=$([ $exit_code -eq 0 ] && echo 'true' || echo 'false')" >> "$GITHUB_OUTPUT"
        echo "time=$(date +%s)" >> "$GITHUB_OUTPUT"

        echo "response<<SLACKCLIEOF" >> "$GITHUB_OUTPUT"
        echo "$output" >> "$GITHUB_OUTPUT"
        echo "SLACKCLIEOF" >> "$GITHUB_OUTPUT"

        if [ $exit_code -ne 0 ]; then
          echo "::error::Slack CLI command failed with exit code $exit_code"
          exit $exit_code
        fi
